// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBaIDXQOybaTqfF7z7jufKllnCC_eKXdE',
    appId: '1:726461962519:web:505782d6546eb1b7b73f52',
    messagingSenderId: '726461962519',
    projectId: 'news-chat-app',
    authDomain: 'news-chat-app.firebaseapp.com',
    storageBucket: 'news-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlkkP4SpARpnXo9w5dZXMRMFG26SEU5h0',
    appId: '1:726461962519:android:c1edd835bdf1bd4bb73f52',
    messagingSenderId: '726461962519',
    projectId: 'news-chat-app',
    storageBucket: 'news-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5eP47dLr2JLv2RxlOzi0dRQl4kgCNEnI',
    appId: '1:726461962519:ios:973f615c949e0c7bb73f52',
    messagingSenderId: '726461962519',
    projectId: 'news-chat-app',
    storageBucket: 'news-chat-app.appspot.com',
    iosClientId: '726461962519-el2aj48crtolni02olpj5pudnms1k7ca.apps.googleusercontent.com',
    iosBundleId: 'com.example.newChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5eP47dLr2JLv2RxlOzi0dRQl4kgCNEnI',
    appId: '1:726461962519:ios:973f615c949e0c7bb73f52',
    messagingSenderId: '726461962519',
    projectId: 'news-chat-app',
    storageBucket: 'news-chat-app.appspot.com',
    iosClientId: '726461962519-el2aj48crtolni02olpj5pudnms1k7ca.apps.googleusercontent.com',
    iosBundleId: 'com.example.newChatApp',
  );
}
